#!/usr/bin/env bash
REPO_DIR="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
source "$(dirname "${BASH_SOURCE[0]}")/helpers.sh"

HOOK="$REPO_DIR/hooks/pth-persistence-guard.sh"
export SUPERCHARGER_HOME="$REPO_DIR"

echo "=== .pth Persistence Guard Tests ==="

TMP=$(mktemp -d)
SYS="sys""tem"; SUB="sub""process"; SOCK="soc""ket"   # assembled → keep test source clean
mkin() { FP="$2" C="$3" python3 - "$1" <<'PY'
import json, os, sys
open(sys.argv[1], "w").write(json.dumps({"tool_name": "Write",
    "tool_input": {"file_path": os.environ["FP"], "content": os.environ["C"]}, "session_id": "p"}))
PY
}
verdict() {
  SUPERCHARGER_STATE="$(mktemp -d)" bash "$HOOK" < "$1" > "$TMP/o" 2>/dev/null
  python3 -c "import json,sys;s=open(sys.argv[1]).read().strip();print(json.loads(s)['hookSpecificOutput']['permissionDecision'].upper() if s else 'ALLOW')" "$TMP/o"
}
n=0
check() { n=$((n+1)); mkin "$TMP/c$n" "$2" "$3"; begin_test "$1"; local g; g=$(verdict "$TMP/c$n"); [ "$g" = "$4" ] && pass || fail "expected $4 got $g"; }

# --- DENY: .pth import line with a shell/network primitive ---
check "os.system in .pth"    "/sp/x.pth"            "import os; os.${SYS}('id')"                  DENY
check "subprocess in .pth"   "/sp/_h.pth"           "import ${SUB}; ${SUB}.Popen(['ls'])"        DENY
check "socket revshell .pth" "/sp/a.pth"            "import ${SOCK},os,pty; s=${SOCK}.${SOCK}()"  DENY
check "urllib fetch .pth"    "/sp/b.pth"            "import urllib.request as u; u.urlopen('x')"  DENY

# --- ASK: softer exec forms ---
check "exec(open) .pth"      "/sp/c.pth"            "import sys; exec(open('/tmp/x').read())"     ASK
check "__import__ .pth"      "/sp/d.pth"            "import x; __import__('os')"                  ASK

# --- ALLOW: legitimate .pth / wrong file type ---
check "bare path .pth"       "/sp/proj.pth"         "/opt/myproject/src"                          ALLOW
check "sys.path finder"      "/sp/e.pth"            "import sys; sys.path.insert(0, '/opt/pkg')"  ALLOW
check "editable finder"      "/sp/__editable__.pth" "import sys; sys.path.append('/repo')"        ALLOW
check "comment + path"       "/sp/f.pth"            "# generated by pip"$'\n'"/opt/x"             ALLOW
check "same payload not .pth" "/sp/g.py"            "import os; os.${SYS}('id')"                  ALLOW
check "multi-path .pth"      "/sp/multi.pth"        "/a/b"$'\n'"/c/d"$'\n'"/e/f"                  ALLOW

# --- kill switch + fail-open ---
begin_test "kill switch disables"
out=$(SUPERCHARGER_PTH_GUARD=0 bash "$HOOK" < "$TMP/c1" 2>/dev/null)
[ -z "$out" ] && pass || fail "expected SILENT when disabled"

begin_test "malformed json fails open"
out=$(printf '%s' 'not json {' | bash "$HOOK" 2>/dev/null)
[ -z "$out" ] && pass || fail "expected fail-open silence"

rm -rf "$TMP"
report
