#!/usr/bin/env bash
REPO_DIR="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
source "$(dirname "${BASH_SOURCE[0]}")/helpers.sh"

HOOK="$REPO_DIR/hooks/generated-file-guard.sh"
export SUPERCHARGER_HOME="$REPO_DIR"

echo "=== Generated File Guard Tests ==="

TMP=$(mktemp -d)
# on-disk files for the header + Edit-target cases
printf '// @generated by graphql-codegen — DO NOT EDIT\nexport type X = {}\n' > "$TMP/gen.ts"
printf 'export const x = 1\n' > "$TMP/normal.ts"

mkin() { TOOL="$2" TIJ="$3" SID="s$4" python3 - "$1" <<'PY'
import json, os, sys
open(sys.argv[1], "w").write(json.dumps({"tool_name": os.environ["TOOL"],
    "tool_input": json.loads(os.environ["TIJ"]), "session_id": os.environ["SID"]}))
PY
}
verdict() {
  SUPERCHARGER_STATE="$(mktemp -d)" bash "$HOOK" < "$1" > "$TMP/o" 2>/dev/null
  python3 -c "import json;s=open('$TMP/o').read().strip();print('ASK' if s and json.loads(s)['hookSpecificOutput']['permissionDecision']=='ask' else 'ALLOW')"
}
n=0
check() { n=$((n+1)); mkin "$TMP/c$n" "$2" "$3" "$n"; begin_test "$1"; local g; g=$(verdict "$TMP/c$n"); [ "$g" = "$4" ] && pass || fail "expected $4 got $g"; }

# --- ASK: generated location / suffix / self-declared header ---
check "dist/ bundle"       Edit  '{"file_path":"/p/dist/bundle.js","old_string":"a","new_string":"b"}'          ASK
check "build/ output"      Edit  '{"file_path":"/p/build/out.js","old_string":"a","new_string":"b"}'            ASK
check "_pb2.py"            Write '{"file_path":"/p/api_pb2.py","content":"# proto"}'                             ASK
check ".pb.go"             Edit  '{"file_path":"/p/schema.pb.go","old_string":"a","new_string":"b"}'            ASK
check "__generated__/"     Edit  '{"file_path":"/p/__generated__/gql.ts","old_string":"a","new_string":"b"}'    ASK
check ".min.js"            Write '{"file_path":"/p/app.min.js","content":"x"}'                                  ASK
check ".g.dart"            Edit  '{"file_path":"/p/model.g.dart","old_string":"a","new_string":"b"}'            ASK
check "@generated header"  Edit  "{\"file_path\":\"$TMP/gen.ts\",\"old_string\":\"X\",\"new_string\":\"Y\"}"     ASK

# --- ALLOW: ordinary source / near-miss names ---
check "normal source"      Edit  "{\"file_path\":\"$TMP/normal.ts\",\"old_string\":\"1\",\"new_string\":\"2\"}"  ALLOW
check "src/index.ts"       Write '{"file_path":"/p/src/index.ts","content":"export const x=1"}'                 ALLOW
check "README.md"          Write '{"file_path":"/p/README.md","content":"# hi"}'                                ALLOW
check "build.gradle"       Edit  '{"file_path":"/p/build.gradle","old_string":"a","new_string":"b"}'            ALLOW
check "hand-written d.ts"  Write '{"file_path":"/p/types/global.d.ts","content":"declare const x: any"}'        ALLOW
check "distribution.py"    Write '{"file_path":"/p/distribution.py","content":"x=1"}'                           ALLOW

# --- dedup, kill, fail-open ---
SS=$(mktemp -d); mkin "$TMP/dd" Write '{"file_path":"/p/dist/x.js","content":"a"}' 88
begin_test "asks first, silent on repeat file (dedup)"
SUPERCHARGER_STATE="$SS" bash "$HOOK" < "$TMP/dd" >/dev/null 2>&1
second=$(SUPERCHARGER_STATE="$SS" bash "$HOOK" < "$TMP/dd" 2>/dev/null)
[ -z "$second" ] && pass || fail "expected SILENT on repeat: $second"
rm -rf "$SS"

begin_test "kill switch disables"
out=$(SUPERCHARGER_GENERATED_FILE_GUARD=0 bash "$HOOK" < "$TMP/c1" 2>/dev/null)
[ -z "$out" ] && pass || fail "expected SILENT when disabled"

begin_test "malformed json fails open"
out=$(printf '%s' 'not json {' | bash "$HOOK" 2>/dev/null)
[ -z "$out" ] && pass || fail "expected fail-open silence"

rm -rf "$TMP"
report
