#!/usr/bin/env bash
# Claude Supercharger — Generated File Guard
# Event: PreToolUse | Matcher: Write, Edit, MultiEdit
#
# Editing a GENERATED/derived file instead of its source is wasted work — the edit
# is silently wiped on the next codegen/build (graphql-codegen, protoc, tsc, a
# bundler), producing a confusing "my fix disappeared" loop. This ASKS before a
# write to a file that declares itself generated (`@generated` / `DO NOT EDIT`
# header — near-zero FP, the file says so) or sits in a generated location
# (dist/build/__generated__/, `*_pb2.py`, `*.pb.go`, `*.g.dart`, `*.generated.*`,
# `*.min.js`). Path-guard's build-artifacts category DENYs a few artifact dirs on
# the Bash channel; this is the tool-channel, ASK-tier, source-of-truth reminder.
# Asks once per file per session. Advisory + fail-open; disable with
# SUPERCHARGER_GENERATED_FILE_GUARD=0.
set -uo pipefail
HOOKS_DIR="${BASH_SOURCE[0]%/*}"
# shellcheck source=hooks/lib-suppress.sh
. "$HOOKS_DIR/lib-suppress.sh" 2>/dev/null || true

[ "${SUPERCHARGER_GENERATED_FILE_GUARD:-1}" = "0" ] && exit 0

# v2.26.35: fork-free stdin read. `$(cat)` forks /bin/cat in EVERY hook —
# ~1.8ms each, and 18 blocking hooks fire per Bash tool call. The trailing
# strip reproduces $(cat)'s newline handling so this is byte-identical.
IFS= read -r -d '' _INPUT || true; _INPUT="${_INPUT%"${_INPUT##*[!$'\n']}"}"
check_hook_disabled "generated-file-guard" 2>/dev/null && exit 0
hook_profile_skip "generated-file-guard" 2>/dev/null && exit 0

_GF_OUT=$(mktemp 2>/dev/null) || _GF_OUT="${TMPDIR:-/tmp}/genfile.$$"
HOOK_INPUT="$_INPUT" python3 -S > "$_GF_OUT" 2>/dev/null <<'PYEOF'
import os, re, sys, json

try:
    d = json.loads(os.environ.get("HOOK_INPUT", ""))
except Exception:
    sys.exit(0)

if (d.get("tool_name") or "") not in ("Write", "Edit", "MultiEdit"):
    sys.exit(0)

ti = d.get("tool_input") or {}
path = ti.get("file_path") or ti.get("notebook_path") or ""
if not path:
    sys.exit(0)
norm = path.replace("\\", "/")
base = norm.rsplit("/", 1)[-1]

# 1. Generated location / suffix (conservative — high-confidence generated).
PATH_RE = re.compile(
    r'(^|/)(dist|build|__generated__|__generated|generated)/|'
    r'\.generated\.[a-z]+$|_pb2\.pyi?$|_pb2_grpc\.py$|\.pb\.go$|\.pb\.gw\.go$|'
    r'\.g\.dart$|\.gen\.go$|\.min\.(js|css)$',
    re.I)
reason = None
if PATH_RE.search(norm):
    reason = "a generated location/type (%s)" % base

# 2. Self-declared @generated header — read the on-disk file (the authoritative
#    signal; near-zero FP because the file literally says so).
if reason is None:
    HEADER_RE = re.compile(
        r'@generated\b|DO NOT EDIT|do not modify this file|code generated by|'
        r'autogenerated|automatically generated|this is a generated file|'
        r'generated by protoc|@codegen', re.I)
    head = ""
    try:
        with open(path, "r", errors="replace") as f:
            head = f.read(2048)
    except Exception:
        head = ""
    # For a brand-new Write, also inspect the incoming content's head.
    if not head and (d.get("tool_name") == "Write"):
        head = (ti.get("content") or "")[:2048]
    if head and HEADER_RE.search(head):
        reason = "a self-declared generated file (@generated / DO NOT EDIT header)"

if reason:
    print(reason)
PYEOF
_REASON=$(cat "$_GF_OUT" 2>/dev/null); rm -f "$_GF_OUT" 2>/dev/null
[ -z "$_REASON" ] && exit 0

SID=$(printf '%s\n' "$_INPUT" | jq -r '.session_id // empty' 2>/dev/null || true); [ -z "$SID" ] && SID="${CLAUDE_CODE_SESSION_ID:-default}"
_FP=$(printf '%s\n' "$_INPUT" | jq -r '.tool_input.file_path // .tool_input.notebook_path // empty' 2>/dev/null || true)
_SEEN="${SUPERCHARGER_STATE:-$HOME/.claude/supercharger}/scope/.genfile-seen-${SID}"
_KEY=$(printf '%s' "$_FP" | cksum 2>/dev/null | cut -d' ' -f1 || echo "$_FP")
if [ -f "$_SEEN" ] && grep -qxF "$_KEY" "$_SEEN" 2>/dev/null; then
  exit 0
fi
mkdir -p "$(dirname "$_SEEN")" 2>/dev/null || true
echo "$_KEY" >> "$_SEEN" 2>/dev/null || true

_MSG="This edits ${_REASON} — changes here are typically overwritten on the next codegen/build run, so the fix will silently disappear. Edit the SOURCE it's generated from (the .proto/.graphql/schema/template or the pre-build source), then regenerate. If editing the output is genuinely intended, confirm. (Disable: SUPERCHARGER_GENERATED_FILE_GUARD=0)"
RSN=$(printf '%s' "$_MSG" | jq -Rs '.' 2>/dev/null || printf '"%s"' "$_MSG")
printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"ask","permissionDecisionReason":%s}}\n' "$RSN"
echo "[Supercharger] generated-file-guard: ASK on edit to a generated file" >&2
exit 0
