#!/usr/bin/env bash
# Claude Supercharger — Plugin settings.json parity seed
# Event: SessionStart | Matcher: —
#
# Closes the last automatic gap between the plugin and the classic install.
#
# A plugin may ship a settings.json, but the plugin reference states that "only the
# `agent` and `subagentStatusLine` keys are currently supported" — so `statusLine`,
# `env.ENABLE_PROMPT_CACHING_1H` and `attribution`, which install.sh writes for a
# classic install, have no declarative plugin equivalent.
#
# WHY THIS HOOK CAN WRITE WHAT THE AGENT CANNOT:
#   path-guard and safety.sh deny any write to settings.json — deliberately, because
#   that is the self-modification protection that stops an agent (or a prompt
#   injection) disabling its own guardrails. Those guards fire on CLAUDE'S TOOL CALLS.
#   A hook is a process Claude Code runs; what it writes internally is never a tool
#   call, so no guard is involved and — crucially — none is ever turned off.
#
#   The rejected alternative was: toggle the kill-switch off, write, toggle back on.
#   It works (verified), and it is exactly the bypass pattern this project exists to
#   prevent. Shipping it would have documented the attack and left a window in which
#   the agent was unguarded. This path has neither property.
#
# CONSENT: never silent. Gated on the `write_settings` userConfig option, which the
# user answers when enabling the plugin. Default is "no" — a plugin writing outside
# its own space is exactly what users do not expect, so it must be asked for, not
# assumed. `/supercharger:setup` and tools/plugin-setup.sh remain the manual paths.
set -uo pipefail

# Honor the global kill-switch (/sc off must silence every hook).
# shellcheck source=hooks/lib-timing.sh
. "${BASH_SOURCE[0]%/*}/lib-timing.sh" 2>/dev/null || true

# Plugin runtime only — the installer already writes these keys.
[ -z "${CLAUDE_PLUGIN_ROOT:-}" ] && exit 0

# Opt-in only.
case "${CLAUDE_PLUGIN_OPTION_WRITE_SETTINGS:-no}" in
  yes|true|1|on) : ;;
  *) exit 0 ;;
esac

# A classic install owns these keys and its statusline.sh is the live one. Repointing
# it at the plugin shim would silently downgrade a working statusline to whatever sits
# in the plugin cache — caught while testing the manual script on a dual-install box.
[ -f "$HOME/.claude/supercharger/hooks/statusline.sh" ] && exit 0

HOOKS_DIR="${BASH_SOURCE[0]%/*}"
# shellcheck source=hooks/lib-paths.sh
. "$HOOKS_DIR/lib-paths.sh" 2>/dev/null || true
: "${SUPERCHARGER_STATE:=${CLAUDE_PLUGIN_DATA:-$HOME/.claude/supercharger}}"

SCOPE="$SUPERCHARGER_STATE/scope"
MARKER="$SCOPE/.settings-seeded"
mkdir -p "$SCOPE" 2>/dev/null || exit 0

# Once only. SessionStart fires every session; re-writing each time would fight a user
# who deliberately removed a key.
[ -f "$MARKER" ] && exit 0

SETTINGS="$HOME/.claude/settings.json"
SHIM="$HOME/.claude/supercharger-statusline.sh"

# The plugin cache path is version-pinned with no `current` symlink, so settings.json
# must point at a stable indirection or it breaks on the next plugin update.
cat > "$SHIM" 2>/dev/null <<'SHIMEOF' || exit 0
#!/usr/bin/env bash
# Generated by Supercharger — stable indirection to the plugin's statusline.
# Resolves by VERSION, not mtime: two cache dirs written in the same second compare
# equal under `-nt`, which pinned an earlier build of this to the OLDER copy.
_sc_paths() {
  local d
  for d in "$HOME/.claude/plugins/cache/"*/claude-supercharger/*/hooks/statusline.sh \
           "$HOME/.claude/plugins/cache/claude-supercharger/"*/*/hooks/statusline.sh; do
    [ -f "$d" ] && printf '%s\n' "$d"
  done
}
newest=$(_sc_paths | sort -u | sort -V 2>/dev/null | tail -1)
[ -n "$newest" ] || newest=$(_sc_paths | sort -u | tail -1)
[ -n "$newest" ] || exit 0    # plugin removed → render nothing, never an error
exec bash "$newest" "$@"
SHIMEOF
chmod 755 "$SHIM" 2>/dev/null || true

# Back up before touching user config — same contract as install.sh.
if [ -f "$SETTINGS" ]; then
  mkdir -p "$HOME/.claude/backups" 2>/dev/null || true
  cp "$SETTINGS" "$HOME/.claude/backups/settings.json.$(date +%Y%m%d-%H%M%S)" 2>/dev/null || true
fi

SETTINGS_FILE="$SETTINGS" SHIM_PATH="$SHIM" python3 - <<'PYEOF' 2>/dev/null || exit 0
import json, os

path = os.environ['SETTINGS_FILE']
shim = os.environ['SHIM_PATH']
try:
    settings = json.load(open(path)) if os.path.exists(path) else {}
except Exception:
    raise SystemExit(0)          # malformed: leave it alone, never make it worse
if not isinstance(settings, dict):
    raise SystemExit(0)

# Never clobber a statusline the user chose for themselves.
if 'statusLine' not in settings:
    settings['statusLine'] = {'type': 'command', 'command': shim}

env = settings.setdefault('env', {})
if isinstance(env, dict):
    env.setdefault('ENABLE_PROMPT_CACHING_1H', '1')

if 'attribution' not in settings:
    settings['attribution'] = {'coAuthoredBy': False}

tmp = path + '.sc-tmp'
with open(tmp, 'w') as f:
    json.dump(settings, f, indent=2)
    f.write('\n')
os.replace(tmp, path)            # atomic: a partial settings.json breaks the session
PYEOF

: > "$MARKER" 2>/dev/null || true
echo "[Supercharger] statusline, 1h prompt cache and attribution written to settings.json (restart to apply). Undo: bash tools/plugin-setup.sh --revert" >&2
exit 0
