#!/usr/bin/env bash
# Claude Supercharger — Hook Catalog Generator
# Reads each hook's header comment ("Event: ... | Matcher: ...") and emits
# a markdown table documenting all installed hooks.
#
# Usage:
#   bash tools/list-hooks.sh           # print to stdout
#   bash tools/list-hooks.sh > docs/HOOKS.md
#   bash tools/list-hooks.sh --check   # verify the committed doc is current (CI)
#
# v2.24.16: --check added because the header of docs/HOOKS.md claims the file is
# auto-generated, while nothing ever verified that it had been regenerated. It had
# not: harness-tamper-guard, bash-injection-scanner and test-mask-guard were absent
# from the catalog users read. Mirrors tools/gen-plugin-hooks.sh --check.

set -uo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOKS_DIR="$REPO_DIR/hooks"
OUT="$REPO_DIR/docs/HOOKS.md"

# Everything below writes to stdout; in --check mode capture it instead and diff.
# generate() keeps the emit logic in one place so the two modes cannot drift.
generate() {

cat <<'HEAD'
# Supercharger Hook Catalog

Auto-generated from hook headers. Run `bash tools/list-hooks.sh > docs/HOOKS.md` to refresh.

## How to disable a hook

Per-project: add to `.supercharger.json`:
```json
{ "disableHooks": ["hook-name", "another-hook"] }
```

Global: add hook name to `~/.claude/supercharger/scope/.disabled-hooks` (one per line).

## Hooks

| Hook | Event | Matcher | Purpose |
|------|-------|---------|---------|
HEAD

for f in "$HOOKS_DIR"/*.sh; do
  name=$(basename "$f" .sh)
  # Skip libraries / helpers (they don't fire as hooks)
  case "$name" in
    lib-*|cmd-normalize|notify-helper|webhook-lib) continue ;;
  esac

  header=$(head -10 "$f" 2>/dev/null)
  event=$(printf '%s\n' "$header" | grep -m1 -E "^# *Event:" | sed -E 's/^# *Event:[[:space:]]*([^|]+).*/\1/' | sed 's/[[:space:]]*$//')
  matcher=$(printf '%s\n' "$header" | grep -m1 -E "^# *Event:" | sed -E 's/.*\| *Matcher:[[:space:]]*//' | sed 's/[[:space:]]*$//')
  # Description: first comment line that's not shebang, not "Claude Supercharger —" header,
  # and not the "Event: X | Matcher: Y" line.
  desc=$(printf '%s\n' "$header" | sed -n '2,8p' \
    | grep -E "^# *[A-Za-z]" \
    | grep -v "^# *Claude Supercharger" \
    | grep -v "^# *Event:" \
    | sed 's/^# *//' \
    | head -1)
  [ -z "$event" ] && event="—"
  [ -z "$matcher" ] && matcher="—"
  [ -z "$desc" ] && desc="(no description)"
  printf '| `%s` | %s | %s | %s |\n' "$name" "$event" "$matcher" "$desc"
done | sort

cat <<'TAIL'

## Standalone tools

Run any of these manually:

| Tool | Purpose |
|------|---------|
TAIL

TOOLS_DIR="$REPO_DIR/tools"
for f in "$TOOLS_DIR"/*.sh; do
  name=$(basename "$f")
  desc=$(head -5 "$f" 2>/dev/null | grep -m1 -E "^# *[A-Za-z]" | sed 's/^# *//' | grep -v "^Claude Supercharger" | head -1)
  [ -z "$desc" ] && desc=$(head -5 "$f" 2>/dev/null | sed -n '2p' | sed 's/^# *//' | head -1)
  [ -z "$desc" ] && desc="(no description)"
  printf '| `tools/%s` | %s |\n' "$name" "$desc"
done | sort

cat <<'FOOT'

---

Generated by `tools/list-hooks.sh`. Last run: see git history of this file.
FOOT

}

if [ "${1:-}" = "--check" ]; then
  if [ ! -f "$OUT" ]; then
    echo "docs/HOOKS.md is missing — run: bash tools/list-hooks.sh > docs/HOOKS.md" >&2
    exit 1
  fi
  if ! diff -q <(generate) "$OUT" >/dev/null 2>&1; then
    echo "docs/HOOKS.md is stale — regenerate: bash tools/list-hooks.sh > docs/HOOKS.md" >&2
    diff <(generate) "$OUT" | head -20 >&2
    exit 1
  fi
  echo "docs/HOOKS.md is up to date."
  exit 0
fi

generate
