#!/usr/bin/env bash
# Claude Supercharger — Plugin parity setup (run by a HUMAN, in a terminal)
#
# Three things a Claude Code plugin cannot do for itself, confirmed against the
# plugin reference: a plugin may ship a settings.json, but "only the `agent` and
# `subagentStatusLine` keys are currently supported". So `statusLine`, `env` and
# `attribution` — which install.sh writes for a classic install — have no plugin
# equivalent. This script closes that gap.
#
# WHY THIS IS NOT RUN BY CLAUDE:
#   Supercharger's own guards (safety.sh selfmod, path-guard) deny any agent write to
#   settings.json. That is deliberate — it is the self-modification protection that
#   stops an agent, or a prompt injection, from disabling its own guardrails. Hooks
#   fire on CLAUDE's tool calls, so a script YOU run in YOUR terminal is unaffected.
#   The correct answer is therefore "the human runs it", exactly as with install.sh.
#
#   Do NOT be tempted by the shortcut of toggling the kill-switch off, writing the
#   file, and toggling it back on. It works, and it is precisely the bypass pattern
#   this project exists to prevent — shipping it would normalise the attack.
#
# Usage:  bash plugin-setup.sh [--dry-run] [--revert]
set -uo pipefail

# Windows python defaults stdout to the ANSI codepage (cp1252) and raises
# UnicodeEncodeError on the box-drawing and arrow characters this tool prints,
# losing ALL of its output. Hooks get this from hooks/lib-paths.sh; tools do not
# reach that file, so they set it themselves. `:=` honours an explicit setting.
: "${PYTHONIOENCODING:=utf-8}"
: "${PYTHONUTF8:=1}"
export PYTHONIOENCODING PYTHONUTF8

DRY_RUN=false
REVERT=false
for a in "$@"; do
  case "$a" in
    --dry-run) DRY_RUN=true ;;
    --revert)  REVERT=true ;;
    -h|--help) sed -n '2,25p' "$0"; exit 0 ;;
    *) echo "Unknown argument: $a" >&2; exit 1 ;;
  esac
done

SETTINGS="$HOME/.claude/settings.json"
SHIM="$HOME/.claude/supercharger-statusline.sh"
BACKUP_DIR="$HOME/.claude/backups"

bold() { printf '\033[1m%s\033[0m\n' "$1"; }
ok()   { printf '  \033[0;32m✓\033[0m %s\n' "$1"; }
warn() { printf '  \033[1;33m!\033[0m %s\n' "$1"; }

# --- Locate the plugin -------------------------------------------------------
# The cache path is VERSION-PINNED (…/claude-supercharger/<version>/) and there is
# no `current` symlink, so settings.json must never point at it directly — it would
# break on the next plugin update. That is what the shim below exists to solve.
find_plugin_statusline() {
  local newest=""
  local d
  for d in "$HOME/.claude/plugins/cache/"*/claude-supercharger/*/hooks/statusline.sh \
           "$HOME/.claude/plugins/cache/claude-supercharger/"*/*/hooks/statusline.sh; do
    [ -f "$d" ] || continue
    if [ -z "$newest" ] || [ "$d" -nt "$newest" ]; then newest="$d"; fi
  done
  printf '%s' "$newest"
}

if [ "$REVERT" = true ]; then
  bold "Reverting plugin parity setup"
  [ -f "$SHIM" ] && { rm -f "$SHIM"; ok "removed $SHIM"; } || warn "no shim to remove"
  echo "  Remove the statusLine / env / attribution keys from $SETTINGS by hand,"
  echo "  or restore a backup from $BACKUP_DIR."
  exit 0
fi

# A classic install already wires all three of these, and its statusline.sh is the
# live one. Repointing settings.json at the plugin shim here would silently DOWNGRADE
# a working classic statusline to whatever version happens to sit in the plugin cache
# — which is exactly what happened on the first dry-run of this script, on a machine
# with both channels present. Refuse rather than "fix" something that isn't broken.
if [ -f "$HOME/.claude/supercharger/hooks/statusline.sh" ]; then
  warn "A classic install is present ($HOME/.claude/supercharger/)."
  warn "It already provides the statusline, prompt-cache and attribution settings."
  warn "This script is only for plugin-ONLY installs — nothing to do. Exiting."
  exit 0
fi

PLUGIN_SL=$(find_plugin_statusline)
if [ -z "$PLUGIN_SL" ]; then
  warn "No plugin install found under ~/.claude/plugins/cache/."
  warn "If you installed with install.sh (classic), you already have all of this —"
  warn "this script is only for plugin installs."
  exit 1
fi
ok "found plugin statusline: $PLUGIN_SL"

# --- 1. Stable shim ----------------------------------------------------------
# Resolves the newest plugin copy AT RUN TIME, so a plugin update cannot orphan the
# settings.json entry.
read -r -d '' SHIM_BODY <<'SHIMEOF' || true
#!/usr/bin/env bash
# Generated by Supercharger plugin-setup.sh — stable indirection to the plugin's
# statusline. The plugin cache path contains the version, so pointing settings.json
# at it directly breaks on every update; this resolves the newest copy each run.
# Pick the highest VERSION, not the newest mtime. mtime looked obvious and is wrong:
# two cache dirs written in the same second compare equal under `-nt`, so an update
# could leave the shim pointed at the older copy (it did, in testing). `sort -V` is
# available on both BSD/macOS and GNU; if it were ever missing, the plain-sort
# fallback still returns a usable path rather than nothing.
_sc_paths() {
  local d
  for d in "$HOME/.claude/plugins/cache/"*/claude-supercharger/*/hooks/statusline.sh \
           "$HOME/.claude/plugins/cache/claude-supercharger/"*/*/hooks/statusline.sh; do
    [ -f "$d" ] && printf '%s\n' "$d"
  done
}
newest=$(_sc_paths | sort -u | sort -V 2>/dev/null | tail -1)
[ -n "$newest" ] || newest=$(_sc_paths | sort -u | tail -1)
[ -n "$newest" ] || exit 0    # plugin removed → render nothing, never an error
exec bash "$newest" "$@"
SHIMEOF

if [ "$DRY_RUN" = true ]; then
  bold "[dry-run] would write $SHIM"
else
  printf '%s\n' "$SHIM_BODY" > "$SHIM" && chmod 755 "$SHIM" && ok "wrote shim: $SHIM"
fi

# --- 2. settings.json --------------------------------------------------------
if [ "$DRY_RUN" = true ]; then
  bold "[dry-run] would set statusLine, env.ENABLE_PROMPT_CACHING_1H, attribution in $SETTINGS"
  exit 0
fi

mkdir -p "$BACKUP_DIR"
STAMP=$(date +%Y%m%d-%H%M%S)
[ -f "$SETTINGS" ] && cp "$SETTINGS" "$BACKUP_DIR/settings.json.$STAMP" && ok "backed up settings.json → $BACKUP_DIR/settings.json.$STAMP"

SETTINGS_FILE="$SETTINGS" SHIM_PATH="$SHIM" python3 <<'PYEOF'
import json, os, sys

path = os.environ['SETTINGS_FILE']
shim = os.environ['SHIM_PATH']
try:
    settings = json.load(open(path)) if os.path.exists(path) else {}
except json.JSONDecodeError:
    print('  ERROR: settings.json is malformed — fix it before running this.', file=sys.stderr)
    sys.exit(1)

changed = []

# Never clobber a statusline the user already chose.
if 'statusLine' not in settings:
    settings['statusLine'] = {'type': 'command', 'command': shim}
    changed.append('statusLine')
else:
    cur = (settings['statusLine'] or {}).get('command', '')
    if cur == shim:
        pass  # already correct — say nothing, so a re-run reads as a no-op
    elif 'supercharger' in cur:
        settings['statusLine'] = {'type': 'command', 'command': shim}
        changed.append('statusLine (repointed at the shim)')
    else:
        print('  ! statusLine already set to something else — left alone')

env = settings.setdefault('env', {})
if 'ENABLE_PROMPT_CACHING_1H' not in env:
    env['ENABLE_PROMPT_CACHING_1H'] = '1'
    changed.append('env.ENABLE_PROMPT_CACHING_1H')

if 'attribution' not in settings:
    settings['attribution'] = {'coAuthoredBy': False}
    changed.append('attribution.coAuthoredBy=false')

json.dump(settings, open(path, 'w'), indent=2)
open(path, 'a').write('\n')
for c in changed:
    print(f'  \033[0;32m✓\033[0m set {c}')
if not changed:
    print('  nothing to change — already configured')
PYEOF

echo
bold "Done. Restart Claude Code (or /reload-plugins) to pick up the statusline."
echo "  Revert with: bash $0 --revert"
